name: garden-app

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://garden_user:${DB_PASSWORD:-garden_password}@db:5432/garden_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
  db:
    container_name: garden-app-db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: garden_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-garden_password}
      POSTGRES_DB: garden_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U garden_user -d garden_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_data:
    name: "garden-app-db-data"