version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://garden_user:garden_password@db:5432/garden_db
    depends_on:
      - db
    volumes:
      - .:/app
      
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=garden_user
      - POSTGRES_PASSWORD=garden_password
      - POSTGRES_DB=garden_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: