name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      run: pytest

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Build changelog
      id: build_changelog
      run: |
        tag=$(echo ${{ github.ref }} | cut -d / -f 3)
        previous_tag=$(git tag --sort=-creatordate | grep -v $tag | head -n 1)
        echo "Changes since $previous_tag:" > CHANGES.md
        echo "" >> CHANGES.md
        git log --pretty=format:"* %s" $previous_tag..$tag >> CHANGES.md
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGES.md
        files: |
          LICENSE
          README.md
          requirements.txt
          docker-compose.yml
        draft: false
        prerelease: false